model_path: "./models/model_rf.pkl"
input_data_path: "./data/raw/heart.csv"
output_data_path: "./data/processed/test_features.csv"
output_target_path: "./data/processed/test_target.csv"
log_params:
    path_to_config: "configs/logging.yaml"