version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_info:
    class: logging.FileHandler
    formatter: simple
    level: DEBUG
    filename: "logs/info_logs.log"

  file_error:
    class: logging.FileHandler
    formatter: simple
    level: ERROR
    filename: "logs/errors_logs.log"

  file_warnings:
    class: logging.FileHandler
    formatter: simple
    level: WARNING
    filename: "logs/warnings_logs.log"

loggers:

  inference:
    level: DEBUG
    handlers:
      - file_info
      - file_warnings
      - file_error
      - console
    propagate: no

  root:
    level: INFO
    handlers:
      - console
      - file_info
      - file_warnings
      - file_error